from selenium import webdriver
from selenium.webdriver.common.by import By 
from selenium.webdriver.edge.options import Options
from selenium.webdriver.common.keys import Keys
import time
import pyotp

# Enter the secret key generated by the Autheticator App
shared_secret_key = "Enter your secret key" 
totp = pyotp.TOTP(shared_secret_key)

edge_options = Options()
edge_options.add_argument("--inprivate")

driver = webdriver.Edge(options=edge_options)
driver.maximize_window()

try:
    driver.get("https://org15dfbbbe.crm11.dynamics.com/main.aspx?appid=44e6c204-5a68-ef11-a66f-6045bdd199dd&pagetype=dashboard&id=eaa6e6bb-4712-ec11-b6e7-00224820f09b&type=system&_canOverride=true")

    time.sleep(3)

    username = driver.find_element(By.ID, "i0116")
    username.send_keys("Enter your username") # Enter your account's username
    username.send_keys(Keys.ENTER)

    time.sleep(3)

    password = driver.find_element(By.ID, "i0118")
    password.send_keys("Enter your password") # Enter your account's password
    password.send_keys(Keys.ENTER)
    
    time.sleep(5)

    otp = totp.now()
    print(f"The generated OTP is: {otp}") 

    time.sleep(3)

    otp_field = driver.find_element(By.ID, "idTxtBx_SAOTCC_OTC")
    otp_field.send_keys(otp)
    otp_field.send_keys(Keys.ENTER)

    time.sleep(5)

    click_yes = driver.find_element(By.ID, "idSIButton9")
    click_yes.click()
    print("Success")

    time.sleep(10)

finally:
    driver.quit()